### ISSUE TITLE
Define minimum viable YAML

### ISSUE THREAD

**Issue by davidgasquez** [datonic/hub#14]
Also, something like the following snipped could allow flexibility.

```yaml
name: atmospheric-carbon-dioxide-trends
version: 1.0.0
kind: FrictionlessDatapackage
kindVersion: 1.0.0
```
