### ISSUE TITLE
IPFS Packages

### ISSUE THREAD

**Issue by davidgasquez** [datonic/hub#6]
This should be possible:

```yaml
name: my-dataset
resources:
  - name: my-data
    type: table
    path: bafkreidgvpkjawlxz6sffxzwgooowe5yt7i6wsyg236mfoks77nywkptdq
    scheme: ipfs
```
